// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSFTPTransfer(arg1) {
  return window['go']['main']['App']['CancelSFTPTransfer'](arg1);
}

export function ChooseAndUploadSFTP(arg1, arg2) {
  return window['go']['main']['App']['ChooseAndUploadSFTP'](arg1, arg2);
}

export function ChooseFilesSFTP() {
  return window['go']['main']['App']['ChooseFilesSFTP']();
}

export function CopySFTP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CopySFTP'](arg1, arg2, arg3, arg4);
}

export function CreateDirectorySFTP(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectorySFTP'](arg1, arg2);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function DeleteSFTP(arg1, arg2) {
  return window['go']['main']['App']['DeleteSFTP'](arg1, arg2);
}

export function DownloadSFTP(arg1, arg2) {
  return window['go']['main']['App']['DownloadSFTP'](arg1, arg2);
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function ListSFTP(arg1, arg2) {
  return window['go']['main']['App']['ListSFTP'](arg1, arg2);
}

export function RenameSFTP(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameSFTP'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveHostSave(arg1, arg2) {
  return window['go']['main']['App']['ResolveHostSave'](arg1, arg2);
}

export function StartSSHSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartSSHSession'](arg1, arg2, arg3, arg4);
}

export function StartTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3);
}

export function StopAllTerminals() {
  return window['go']['main']['App']['StopAllTerminals']();
}

export function StopTerminal(arg1) {
  return window['go']['main']['App']['StopTerminal'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function TrackCommand(arg1) {
  return window['go']['main']['App']['TrackCommand'](arg1);
}

export function UploadClipboardFileSFTP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadClipboardFileSFTP'](arg1, arg2, arg3, arg4);
}

export function UploadPathsSFTP(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadPathsSFTP'](arg1, arg2, arg3);
}

export function UpsertHost(arg1) {
  return window['go']['main']['App']['UpsertHost'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
