// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSFTPTransfer(arg1:string):Promise<boolean>;

export function ChooseAndUploadSFTP(arg1:string,arg2:string):Promise<number>;

export function ChooseFilesSFTP():Promise<Array<string>>;

export function CopySFTP(arg1:string,arg2:Array<string>,arg3:string,arg4:boolean):Promise<void>;

export function CreateDirectorySFTP(arg1:string,arg2:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<Array<main.Host>>;

export function DeleteSFTP(arg1:string,arg2:Array<string>):Promise<void>;

export function DownloadSFTP(arg1:string,arg2:string):Promise<string>;

export function GetHosts():Promise<Array<main.Host>>;

export function ListSFTP(arg1:string,arg2:string):Promise<main.SFTPListing>;

export function RenameSFTP(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveHostSave(arg1:string,arg2:boolean):Promise<Array<main.Host>>;

export function StartSSHSession(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function StartTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StopAllTerminals():Promise<void>;

export function StopTerminal(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<Array<main.Host>>;

export function TrackCommand(arg1:string):Promise<main.ConnectionCommand>;

export function UploadClipboardFileSFTP(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadPathsSFTP(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function UpsertHost(arg1:main.Host):Promise<Array<main.Host>>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
